### ISSUE TITLE
sprites file is empty

### ISSUE THREAD

**Issue by rajkhatri** [mllrsohn/sprite-brunch#12]
Hi,

I am using Phoenix with this to attempt to create a `sprites.scss` file. My directories are all set, and I still can't seem to get a `.scss` file that is not empty. Everything I have tried, creates an empty scss file.

This is what I have in my `brunch-config.js` file:

```
exports.config = {
  files: { ... },
  conventions: { ... },
  paths: { ... },
  plugins: {
    babel: { ... },
    sass: { ... },
    sprites: {
      path: 'static/images/sprites', // Path to your sprites folder
      destCSS: 'css/sprites.scss', // Destination sass/less/stylus files
      destSprites: 'static/images', // Destination of generated sprite files
      cssFormat: 'scss', // less, sass, scss, stylus
      algorithm: 'top-down', // algorithm: top-down, left-right, diagonal (\ format), alt-diagonal
      engine: 'pixelsmith', // pixelsmith, canvassmith, gmsmith
      imgOpts: {
        format: 'auto', // auto, jpg, png (If auto is used and there is png and jpg in a folder the sprite will be jpg)
        quality: 90 // Quality of the output image
      }
    }
  },
  modules: { ... },
  npm: { ... }
};
```
The `sprites.scss` file gets created, but is empty in the above path. The image below is the folder structure.
<img width="146" alt="screen shot 2017-04-10 at 3 05 07 pm" src="https://cloud.githubusercontent.com/assets/9418005/24884629/27a25580-1dff-11e7-9bb3-dc6d881aeed8.png">

I have been working on this since last thursday with several other team members, and we are not sure what we are doing wrong. Any help would be appreciated. Thanks

**Comment by aedryan** [comment]
The issue is likely that sprite-brunch expects you to categorize your sprite images.  Assuming that your sprites folder is full of images, categorize those images into subfolders.  Such as /static/images/sprites/icons/icon-image.png.

**Comment by rajkhatri** [comment]
Thanks for the response. That was exactly it. Is there a way to support `.svg` files as well as `.png`'s?

**Comment by aedryan** [comment]
Sprite-brunch relies on [spritesmith](https://github.com/Ensighten/spritesmith) for processing the images.  It doesn't support svg however there are several issues like [this one](https://github.com/Ensighten/spritesmith/issues/36) with spritesmith about this that offer helpful suggestions for handling svg.
