### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by wulymammoth** [mllrsohn/sprite-brunch#13]
I'm trying to generate sprites along with the mixins to use them, but I am unable to figure out what each of the comments below mean:

### My current config:
```js
sprites: {
      path: 'static/images/sprites', // Path to your sprites folder
      destCSS: 'css/sprites.scss', // Destination sass/less/stylus files
      destSprites: 'static/images', // Destination of generated sprite files
      cssFormat: 'scss', // less, sass, scss, stylus
      algorithm: 'top-down', // algorithm: top-down, left-right, diagonal (\ format), alt-diagonal
      engine: 'pixelsmith', // pixelsmith, canvassmith, gmsmith
      imgOpts: {
        format: 'auto', // auto, jpg, png (If auto is used and there is png and jpg in a folder the sprite will be jpg)
        quality: 90 // Quality of the output image
      }
```

### This gets created in our `sprites.scss` mixin file and it doesn't seem correct:
```scss
$jewelry-board-logo-image: './static/images/icons-790347d5434fb63538538ef5702ebb0cbf8ec9c1.png';
```

### This is my project's directory structure (in case you're wondering):
![image](https://cloud.githubusercontent.com/assets/861147/24984784/93de9956-1fa4-11e7-84fd-b56faa2024f0.png)

### Please, help me clarify the following keys:
- **path**: source of images to be sprited
- **destCSS**: the compiled stylesheet (doesn't matter which pre-processor)
- **destSprites**: the location at which the generated sprite-sheet should end up
- **cssFormat**: (this one is super confusing) is this the pre-processor or what we want to output?

**Comment by aedryan** [comment]
# path 
Sounds like you've got this one.  This is the location of your images that you want to spritesmith.  So if you're images are in /assets/static/images/sprites/ then that is what to use for that key.  Note that sprite-brunch expects your images to be categorized into sub-folders so the aforementioned folder should contain folders of images; e.g.: /assets/static/images/sprites/icons/icon.png.

# destCSS
Also sounds like you've got this one.  This is where the spritesheet CSS is written.  

# destSprites
Also sounds like you've got this one.  This is where the spritesheet image files are written.

# cssFormat
This is the format of the pre-processor.  

I'm not sure how to help with the incorrect image variable.

**Comment by wulymammoth** [comment]
@aedryan thanks for the help! I'll give it another try tomorrow and, if you don't mind, I'll update the README to reflect our discussion if that's okay.

**Comment by aedryan** [comment]
Sure make a pull request.
