### ISSUE TITLE
can't establish sass directory

### ISSUE THREAD

**Issue by heaversm** [mllrsohn/sprite-brunch#7]
Hi - I can't seem to set up a config file to target the proper directory for sass files. I can generate sprites, but not the sass. Here's my directory structure for images to be converted to sprites:

`app > assets > images > sprites > [folders of sprites]`

and here is my directory for styles:

`app > styles`

so I would think the config would be:

```
sprites:
    path: 'app/assets/images/sprites' # Path to your sprites folder
    destCSS: 'app/styles/_sprites.scss' # Destination sass files for sprites
```

but I get the error:

`Could not write stylesheet, please make sure the path exists`

**Comment by aedryan** [comment]
This was an issue with the stylesheet path having to be in place before it's file can be written.  It is fixed in the latest version with the inclusion of mkdirp.
