### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by axebox** [mllrsohn/sprite-brunch#9]
```
npm install --save-dev sprite-brunch
npm ERR! git rev-list -n1 bug/false.negative.for.jpeg: fatal: ambiguous argument 'bug/false.negative.for.jpeg': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 bug/false.negative.for.jpeg: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 bug/false.negative.for.jpeg: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 bug/false.negative.for.jpeg:
```

Any ideas?

**Comment by hnb2** [comment]
I have the same problem, apparently it comes from the dependency "canvas", the branch comes from a [PR](https://github.com/Automattic/node-canvas/pull/271). This PR is from 2013, so I am guessing there is an old dependency.

**Comment by aedryan** [comment]
This should be fixed with the new version of the module.  It uses the latest spritesmith which relies on node's built in pixelsmith by default.
